version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: build

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      include: scope
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"
