services:
  registry:
    restart: always
    image: registry:2.8.3
    ports:
      - "5005:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: true
    volumes:
      - ./.registry:/var/lib/registry/docker/registry/v2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5005/v2/" ]
