name: Lint

on:
  pull_request:
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [ milestoned, opened, edited, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Checks
    permissions:
      pull-requests: read # Allows reading pull request metadata.
      contents: read  # Allows pulling repo contents.

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - name: Cache Gradle packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Run API Check
        run: ./gradlew apiCheck

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

      - name: Run Detekt
        run: ./gradlew detekt
