name: Unit Tests
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 21
          cache: "gradle"

      - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          make install-deps
          make test

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: kotlin-test-results
          path: |
            ${{ github.workspace }}/build/reports/tests/
